// CATEGORY
export const GETTING_CATEGORIES = 'GETTING_CATEGORIES';
export const GETTING_CATEGORIES_SUCCESS = 'GETTING_CATEGORIES_SUCCESS';
export const GETTING_CATEGORIES_FAILURE = 'GETTING_CATEGORIES_FAILURE';
export const GETTING_CATEGORY = 'GETTING_CATEGORY';
export const GETTING_CATEGORY_SUCCESS = 'GETTING_CATEGORY_SUCCESS';
export const GETTING_CATEGORY_FAILURE = 'GETTING_CATEGORY_FAILURE';

// POST
export const ADDING_POST = 'ADDING_POST';
export const ADDING_POST_SUCCESS = 'ADDING_POST_SUCCESS';
export const ADDING_POST_FAILURE = 'ADDING_POST_FAILURE';
export const GETTING_POSTS = 'GETTING_POSTS';
export const GETTING_POSTS_SUCCESS = 'GETTING_POSTS_SUCCESS';
export const GETTING_POSTS_FAILURE = 'GETTING_POSTS_FAILURE';
export const DELETING_POST = 'DELETING_POST';
export const DELETING_POST_SUCCESS = 'DELETING_POST_SUCCESS';
export const DELETING_POST_FAILURE = 'DELETING_POST_FAILURE';
export const GETTING_POST = 'GETTING_POST';
export const GETTING_POST_SUCCESS = 'GETTING_POST_SUCCESS';
export const GETTING_POST_FAILURE = 'GETTING_POST_FAILURE';
export const UPDATING_POST = 'UPDATING_POST';
export const UPDATING_POST_SUCCESS = 'UPDATING_POST_SUCCESS';
export const UPDATING_POST_FAILURE = 'UPDATING_POST_FAILURE';
export const VOTING_POST = 'VOTING_POST';
export const VOTING_POST_SUCCESS = 'VOTING_POST_SUCCESS';
export const VOTING_POST_FAILURE = 'VOTING_POST_FAILURE';

// COMMENT
export const ADDING_COMMENT = 'ADDING_COMMENT';
export const ADDING_COMMENT_SUCCESS = 'ADDING_COMMENT_SUCCESS';
export const ADDING_COMMENT_FAILURE = 'ADDING_COMMENT_FAILURE';
export const GETTING_COMMENTS = 'GETTING_COMMENTS';
export const GETTING_COMMENTS_SUCCESS = 'GETTING_COMMENTS_SUCCESS';
export const GETTING_COMMENTS_FAILURE = 'GETTING_COMMENTS_FAILURE';
export const DELETING_COMMENT = 'DELETING_COMMENT';
export const DELETING_COMMENT_SUCCESS = 'DELETING_COMMENT_SUCCESS';
export const DELETING_COMMENT_FAILURE = 'DELETING_COMMENT_FAILURE';
export const GETTING_COMMENT = 'GETTING_COMMENT';
export const GETTING_COMMENT_SUCCESS = 'GETTING_COMMENT_SUCCESS';
export const GETTING_COMMENT_FAILURE = 'GETTING_COMMENT_FAILURE';
export const UPDATING_COMMENT = 'UPDATING_COMMENT';
export const UPDATING_COMMENT_SUCCESS = 'UPDATING_COMMENT_SUCCESS';
export const UPDATING_COMMENT_FAILURE = 'UPDATING_COMMENT_FAILURE';
export const VOTING_COMMENT = 'VOTING_COMMENT';
export const VOTING_COMMENT_SUCCESS = 'VOTING_COMMENT_SUCCESS';
export const VOTING_COMMENT_FAILURE = 'VOTING_COMMENT_FAILURE';
