export const ADDING_POST = 'ADDING_POST';
export const ADDING_POST_SUCCESS = 'ADDING_POST_SUCCESS';
export const ADDING_POST_FAILURE = 'ADDING_POST_FAILURE';
export const GETTING_POSTS = 'GETTING_POSTS';
export const GETTING_POSTS_SUCCESS = 'GETTING_POSTS_SUCCESS';
export const GETTING_POSTS_FAILURE = 'GETTING_POSTS_FAILURE';
